<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5L9D1ND" name="iSimpleMaven.iSimpleMavenTestNg" tests="7" failures="1" timestamp="6 May 2018 22:19:27 GMT" time="0.013" errors="0">
  <testcase name="SampleTestScript6" time="0.000" classname="iSimpleMaven.iSimpleMavenTestNg"/>
  <testcase name="SampleTestScript2" time="0.009" classname="iSimpleMaven.iSimpleMavenTestNg">
    <failure type="java.lang.AssertionError" message="expected [Hello] but found [Google]">
      <![CDATA[java.lang.AssertionError: expected [Hello] but found [Google]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:496)
	at org.testng.Assert.assertEquals(Assert.java:125)
	at org.testng.Assert.assertEquals(Assert.java:178)
	at org.testng.Assert.assertEquals(Assert.java:188)
	at iSimpleMaven.iSimpleMavenTestNg.SampleTestScript2(iSimpleMavenTestNg.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1191)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)
	at org.testng.TestNG.run(TestNG.java:1024)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- SampleTestScript2 -->
  <testcase name="SampleTestScript4" time="0.001" classname="iSimpleMaven.iSimpleMavenTestNg"/>
  <testcase name="SampleTestScript1" time="0.000" classname="iSimpleMaven.iSimpleMavenTestNg"/>
  <testcase name="SampleTestScript5" time="0.001" classname="iSimpleMaven.iSimpleMavenTestNg"/>
  <testcase name="SampleTestScript7" time="0.001" classname="iSimpleMaven.iSimpleMavenTestNg"/>
  <testcase name="SampleTestScript3" time="0.001" classname="iSimpleMaven.iSimpleMavenTestNg"/>
</testsuite> <!-- iSimpleMaven.iSimpleMavenTestNg -->
